# Generated by Django 6.0.3 on 2026-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_role_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
    ]
