# Generated by Django 6.0.3 on 2026-06-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tax_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time in minutes', null=True),
        ),
    ]
